language: scala
scala:
  - 2.12.12
  - 2.13.3
jdk:
  - oraclejdk8
script: sbt clean test
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
notifications:
  slack: thenewmotion:AXSluctig1mmZbeKRDeeY41s
